name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x

    - name: Build WASM
      run: wasm-pack build --release

    - name: Build Webpack
      working-directory: ./www
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www/dist
